drop table account if exists;
drop table client if exists;
create table account (
    id integer generated by default as identity, balance bigint not null check (balance>=0),
    natural_id integer not null check (natural_id>=0), version bigint not null,
    client integer not null,
    primary key (id));
create table client (
    id integer generated by default as identity,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (id));
alter table account add constraint balance_naturalid_client_unique_constraint unique (balance, natural_id, client);
alter table client add constraint email_unique_constraint unique (email);
alter table account add constraint FK_account_client foreign key (client) references client;
