drop table account if exists;
drop table client if exists;
create table account (id integer generated by default as identity, balance bigint not null check (balance>=0), natural_id integer not null check (natural_id>=0), version bigint not null, client integer not null, primary key (id));
create table client (id integer generated by default as identity, email varchar(255) not null, password varchar(255) not null, primary key (id));
alter table account add constraint UKd9itvlaj5rbpnpj7nw0keq61k unique (balance, natural_id, client);
alter table client add constraint UK_bfgjs3fem0hmjhvih80158x29 unique (email);
alter table account add constraint FKp4traw23086e5apisdb35r2n3 foreign key (client) references client;