create table transaction
    (id integer generated by default as identity,
    amount bigint not null,
    balance_before bigint not null,
    operation_name varchar(255) not null,
    timestamp timestamp not null,
    account integer not null,
    primary key (id));
alter table transaction add constraint FK_transaction_account foreign key (account) references account;